services:
  - type: web
    name: best-ges-comptes
    runtime: docker
    plan: free
    buildCommand: "docker build -t best-ges-comptes ."
    startCommand: "docker run -p $PORT:80 best-ges-comptes"
    envVars:
      - key: APP_NAME
        value: BestGesComptes
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        generateValue: true
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: pgsql
          name: best-ges-comptes-db
          property: host
      - key: DB_PORT
        fromService:
          type: pgsql
          name: best-ges-comptes-db
          property: port
      - key: DB_DATABASE
        fromService:
          type: pgsql
          name: best-ges-comptes-db
          property: database
      - key: DB_USERNAME
        fromService:
          type: pgsql
          name: best-ges-comptes-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pgsql
          name: best-ges-comptes-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file

  - type: pgsql
    name: best-ges-comptes-db
    plan: free
    ipAllowList: []